import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import React, { useMemo, useState } from 'react';
import { Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import Toast from 'react-native-toast-message';
import FileNameText from '../../components/FileNameText';
import { useThemeColors } from '../../hooks/useThemeColors';
import { apiClient } from '../../services/api';
import { dedupeCitations } from '../../utils/dedupeCitations';

export interface CitationItem {
  source_type?: string;
  source_name?: string;
  filename?: string;
  excerpt?: string;
  chunk_content?: string;
  snippet?: string;
  document_id?: number | string;
  source_id?: string | number;
  paragraph?: string;
  paragraph_start?: number;
  paragraph_end?: number;
  relevance_score?: number;
  cite_index?: number;
}

export interface ChatMessageFooterProps {
  /** Chat history id (e.g. selectedChat.id) */
  chatHistoryId?: number;
  /** Index of the user+assistant pair (0-based) */
  messagePairIndex: number;
  /** Previous user message content (query) */
  queryText?: string;
  /** Assistant response content */
  responseText: string;
  /** Message timestamp for display */
  createdAt: string;
  /** Sources/citations/references for this response (shown in sources dialog) */
  citations?: CitationItem[] | null;
  /** Initial feedback state from server (1 = up, -1 = down, null = none) */
  initialFeedbackScore?: number | null;
  /** Called after feedback is submitted so parent can persist */
  onFeedbackSubmitted?: (score: number | null) => void;
  /** When false, hide like / dislike / citation (e.g. for user or workspace chat). Default true. */
  showActions?: boolean;
  /** Show retry (same backend as web: retry + retry_replace_message_id) */
  showRetry?: boolean;
  onRetry?: () => void;
  retryDisabled?: boolean;
  /** More sources — additional_response_for_message_id flow (append, not replace) */
  showMoreSources?: boolean;
  onMoreSources?: () => void;
  moreSourcesDisabled?: boolean;
}

/** Plain-text body for copy/share — label on its own line, content below. */
function buildShareBodyPlain(query: string | undefined, response: string): string {
  const q = query?.trim();
  if (q) {
    return `You:\n${q}\n\nChatGD:\n${response}`;
  }
  return response;
}

function buildChatGDCopyText(queryText: string | undefined, responseText: string): string {
  const now = new Date();
  const dateTimeDisplay = `${now.toLocaleDateString()} ${now.toLocaleTimeString()}`;
  const body = buildShareBodyPlain(queryText, responseText);
  return `GrabDocs — ChatGD Response\n${dateTimeDisplay}\n\n${body}\n\nGenerated by GrabDocs`;
}

function formatTime(dateString: string): string {
  try {
    if (!dateString) return '';
    const iso = dateString.includes('Z') || /[+-]\d{2}:\d{2}$/.test(dateString)
      ? dateString
      : dateString + (dateString.includes('T') ? 'Z' : '');
    const date = new Date(iso);
    if (isNaN(date.getTime())) return '';
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  } catch {
    return '';
  }
}

export function ChatMessageFooter({
  chatHistoryId,
  messagePairIndex,
  queryText,
  responseText,
  createdAt,
  citations = null,
  initialFeedbackScore = null,
  onFeedbackSubmitted,
  showActions = true,
  showRetry = false,
  onRetry,
  retryDisabled = false,
  showMoreSources = false,
  onMoreSources,
  moreSourcesDisabled = false,
}: ChatMessageFooterProps) {
  const colors = useThemeColors();
  const [feedbackScore, setFeedbackScore] = useState<number | null>(initialFeedbackScore ?? null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showSourcesModal, setShowSourcesModal] = useState(false);
  const sourceList = useMemo(
    () => (citations && citations.length > 0 ? dedupeCitations(citations) : []),
    [citations],
  );

  const handleCopyResponse = async () => {
    if (!responseText) return;
    try {
      const text = buildChatGDCopyText(queryText, responseText);
      await Clipboard.setStringAsync(text);
      Toast.show({ type: 'success', text1: 'Copied to clipboard!' });
    } catch {
      Toast.show({ type: 'error', text1: 'Failed to copy' });
    }
  };

  const submitFeedback = async (score: number) => {
    if (isSubmitting) return;
    const newScore = feedbackScore === score ? null : score;
    const scoreToSend = newScore === null ? 0 : newScore;

    setIsSubmitting(true);
    setFeedbackScore(newScore);

    try {
      await apiClient.submitChatFeedback({
        chat_history_id: chatHistoryId,
        message_pair_index: messagePairIndex,
        query_text: queryText,
        response_text: responseText,
        feedback_score: scoreToSend,
        workspace_id: null,
        conversation_id: null,
      });
      onFeedbackSubmitted?.(newScore);
    } catch {
      setFeedbackScore(feedbackScore);
      Toast.show({ type: 'error', text1: 'Failed to submit feedback' });
    } finally {
      setIsSubmitting(false);
    }
  };

  const iconColor = colors.textSecondary ?? '#666';
  const activeUp = feedbackScore === 1 ? '#22c55e' : iconColor;
  const activeDown = feedbackScore === -1 ? '#f97316' : iconColor;

  return (
    <View style={[styles.row, styles.footerBelowResponse]}>
      {showActions && (
        <View style={styles.icons}>
          {/* Web order: Retry (circular arrow) → More sources (circle +) → Share → thumbs → Sources */}
          {showRetry && onRetry ? (
            <TouchableOpacity
              onPress={onRetry}
              disabled={retryDisabled}
              style={styles.iconBtn}
              hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
              accessibilityLabel="Retry response"
              accessibilityRole="button"
            >
              <Ionicons
                name="refresh-outline"
                size={20}
                color={retryDisabled ? (colors.textLight ?? '#ccc') : iconColor}
              />
            </TouchableOpacity>
          ) : null}
          {showMoreSources && onMoreSources ? (
            <TouchableOpacity
              onPress={onMoreSources}
              disabled={moreSourcesDisabled}
              style={styles.iconBtn}
              hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
              accessibilityLabel="Add more sources"
              accessibilityRole="button"
            >
              <Ionicons
                name="add-circle-outline"
                size={20}
                color={moreSourcesDisabled ? (colors.textLight ?? '#ccc') : iconColor}
              />
            </TouchableOpacity>
          ) : null}
          <TouchableOpacity
            onPress={handleCopyResponse}
            disabled={!responseText}
            style={styles.iconBtn}
            hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
            accessibilityLabel="Copy response"
            accessibilityRole="button"
          >
            <Ionicons name="copy-outline" size={18} color={iconColor} />
          </TouchableOpacity>
          <TouchableOpacity
            onPress={() => submitFeedback(1)}
            disabled={isSubmitting}
            style={styles.iconBtn}
            hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
            accessibilityLabel={feedbackScore === 1 ? 'Remove helpful vote' : 'Mark as helpful'}
            accessibilityRole="button"
          >
            <MaterialCommunityIcons
              name={feedbackScore === 1 ? 'thumb-up' : 'thumb-up-outline'}
              size={20}
              color={activeUp}
            />
          </TouchableOpacity>
          <TouchableOpacity
            onPress={() => submitFeedback(-1)}
            disabled={isSubmitting}
            style={styles.iconBtn}
            hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
            accessibilityLabel={feedbackScore === -1 ? 'Remove unhelpful vote' : 'Mark as unhelpful'}
            accessibilityRole="button"
          >
            <MaterialCommunityIcons
              name={feedbackScore === -1 ? 'thumb-down' : 'thumb-down-outline'}
              size={20}
              color={activeDown}
            />
          </TouchableOpacity>
          <TouchableOpacity
            onPress={() => setShowSourcesModal(true)}
            style={styles.iconBtn}
            hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
            accessibilityLabel={sourceList.length > 0 ? `View ${sourceList.length} sources` : 'View sources'}
            accessibilityRole="button"
          >
            <Ionicons
              name="book-outline"
              size={20}
              color={sourceList.length > 0 ? iconColor : (colors.textLight ?? '#999')}
            />
          </TouchableOpacity>
        </View>
      )}
      <Text style={[styles.timestamp, { color: iconColor }]} numberOfLines={1}>
        {formatTime(createdAt)}
      </Text>

      <Modal
        visible={showSourcesModal}
        transparent
        animationType="fade"
        onRequestClose={() => setShowSourcesModal(false)}
      >
        <TouchableOpacity
          activeOpacity={1}
          style={styles.modalOverlay}
          onPress={() => setShowSourcesModal(false)}
        >
          <TouchableOpacity activeOpacity={1} onPress={(e) => e.stopPropagation()} style={[styles.sourcesModal, { backgroundColor: colors.card }]}>
            <View style={[styles.sourcesModalHeader, { borderBottomColor: colors.border }]}>
              <Text style={[styles.sourcesModalTitle, { color: colors.text }]}>Sources</Text>
              <TouchableOpacity
                onPress={() => setShowSourcesModal(false)}
                hitSlop={12}
                accessibilityLabel="Close sources"
                accessibilityRole="button"
              >
                <Ionicons name="close" size={24} color={colors.text} />
              </TouchableOpacity>
            </View>
            <ScrollView style={styles.sourcesModalScroll} contentContainerStyle={styles.sourcesModalContent}>
              {sourceList.length === 0 ? (
                <Text style={[styles.sourcesEmpty, { color: colors.textSecondary }]}>No sources for this response.</Text>
              ) : (
                sourceList.map((item, index) => {
                  const name = item.source_name || item.filename || item.source_type || `Source ${index + 1}`;
                  const data = (item.chunk_content || item.excerpt || '').trim();
                  return (
                    <View key={index} style={[styles.sourceItem, { borderBottomColor: colors.border }]}>
                      <FileNameText
                        name={name}
                        style={[styles.sourceName, { color: colors.text }]}
                      />
                      {data ? (
                        <>
                          <Text style={[styles.sourceDataLabel, { color: colors.textSecondary }]}>Data</Text>
                          <Text style={[styles.sourceExcerpt, { color: colors.textSecondary }]} numberOfLines={6}>
                            {data}
                          </Text>
                        </>
                      ) : null}
                    </View>
                  );
                })
              )}
            </ScrollView>
          </TouchableOpacity>
        </TouchableOpacity>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  footerBelowResponse: {
    marginTop: 12,
  },
  icons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  iconBtn: {
    padding: 4,
  },
  timestamp: {
    fontSize: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 24,
  },
  sourcesModal: {
    maxHeight: '70%',
    borderRadius: 12,
    overflow: 'hidden',
  },
  sourcesModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  sourcesModalTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  sourcesModalScroll: {
    maxHeight: 400,
  },
  sourcesModalContent: {
    padding: 16,
    paddingBottom: 24,
  },
  sourcesEmpty: {
    fontSize: 15,
    textAlign: 'center',
    paddingVertical: 24,
  },
  sourceItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  sourceName: {
    fontSize: 16,
    fontWeight: '500',
  },
  sourceDataLabel: {
    fontSize: 12,
    fontWeight: '600',
    marginTop: 6,
    marginBottom: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  sourceExcerpt: {
    fontSize: 13,
    marginTop: 4,
    lineHeight: 18,
  },
});
